### ISSUE TITLE
Latest Quest Module Causes Error

### ISSUE THREAD

**Issue by Relaxing9** [BerndiVader/MythicMobsQuestsModule#37]
When Running Build Number 6 for MythicMobsQuests, the module generates this error:

`[13:21:34] [Server thread/INFO]: [Quests] Loaded 4 Quest(s), 8 Event(s), 880 Phrase(s)
[13:21:34] [Server thread/INFO]: [Quests] Loaded Module: Kill MythicMobs Objective by BerndiVader
[13:21:34] [Server thread/INFO]: [Quests] Registered events for custom objective "Kill MythicMobs Objective"
[13:21:34] [Server thread/INFO]: [Quests] Loaded Module: Custom Denizen by [Unknown]
[13:21:34] [Server thread/ERROR]: [Quests] Plugin Quests v3.6.8-b747 has failed to register events for class com.gmail.berndivader.mythicmobsquests.DenizenCustomObjective because com/gmail/berndivader/mythicdenizenaddon/events/CustomObjectiveEvent does not exist.
[13:21:34] [Server thread/INFO]: [Quests] Registered events for custom objective "Custom Denizen"
[13:21:34] [Server thread/INFO]: [Quests] Loaded Module: MythicMobs Item Require by BerndiVader, idea Wahrheit
[13:21:34] [Server thread/INFO]: [Quests] Loaded Module: MythicMobs Item Reward by BerndiVader
[13:21:34] [Server thread/WARN]: [Quests] Task #56 for Quests v3.6.8-b747 generated an exception
java.lang.NoClassDefFoundError: com/gmail/berndivader/mythicdenizenaddon/events/CustomObjectiveEvent$Action
	at com.gmail.berndivader.mythicmobsquests.DenizenCustomObjective$1.<clinit>(DenizenCustomObjective.java:60) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
	at me.blackvein.quests.Quests.loadModule(Quests.java:572) ~[?:?]
	at me.blackvein.quests.Quests.loadModules(Quests.java:513) ~[?:?]
	at me.blackvein.quests.Quests$1.run(Quests.java:486) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [Spigot.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [Spigot.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [Spigot.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [Spigot.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [Spigot.jar:git-Spigot-8043ebc-02b466c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.gmail.berndivader.mythicdenizenaddon.events.CustomObjectiveEvent$Action
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.net.FactoryURLClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	... 13 more`

Note that I do not use Denizen nor do I want to use Denizen, can you fix this issue to catch if Denizen is a plugin on my server and if not try not to making a custom denizen event.
Quests Version: 3.6.8 (Build 747)
MythicMobsQuestsModule: MythicMobsQuests-366-SNAPSHOT.jar (Build Number 6) [May 9, 2019 2:12 PM]
Spigot Version: git-Spigot-8043ebc-02b466c (MC: 1.14.1)

**Comment by BerndiVader** [comment]
You are right. I will rethink this and push a fix asap.

**Comment by BerndiVader** [comment]
its fixed with 38987ac

**Comment by Relaxing9** [comment]
> its fixed with [38987ac](https://github.com/BerndiVader/MythicMobsQuestsModule/commit/38987ac33c8d42604e664da2830ef1297dd9d91e)

Indeed it is fixed, thank you for that.

**Comment by ghost** [comment]
@BerndiVader even with the latest release, I'm still experiencing that exact same issue.

Similar to Relaxing9's issue, I don't use Denizen nor do I want to use Denizen. I do not have a "Custom Denizen" reference anywhere in my quests.yml, I've triple-checked.
