### ISSUE TITLE
Quests cant detect when mythicmob is killed

### ISSUE THREAD

**Issue by yash-mathur** [BerndiVader/MythicMobsQuestsModule#42]
MythicMobs - 4.9.0
Quests - Quests-3.9.2
MythicMobsQuests-391-SNAPSHOT

ERROR Could not pass event EntityDeathEvent to Quests v3.9.2-b94
11.04 22:23:40 [Server] INFO java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
11.04 22:23:40 [Server] INFO at com.gmail.berndivader.mythicmobsquests.NMSUtils.getActiveMobLevel(NMSUtils.java:122) ~[?:?]
11.04 22:23:40 [Server] INFO at com.gmail.berndivader.mythicmobsquests.MythicMobsKillObjective.onMythicMobDeathEvent(MythicMobsKillObjective.java:60) ~[?:?]
11.04 22:23:40 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor728.execute(Unknown Source) ~[?:?]
11.04 22:23:40 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:776) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.World.a(World.java:862) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:508) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1260) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1127) ~[patched_1.15.2.jar:git-Paper-168]
11.04 22:23:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:935) ~[patched_1.15.2.jar:git-Paper-168]

**Comment by Yukitty** [comment]
This should be fixed as of #41

**Comment by SauROnmiKE** [comment]
Can confirm that it's still happening with the latest version of the module.
